# Generated by Django 4.2.9 on 2026-02-15 21:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClapTestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('subjective', 'Subjective / Essay'), ('text_block', 'Text Block / Instructions'), ('audio_block', 'Audio Block'), ('file_upload', 'File Upload')], max_length=50)),
                ('order_index', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clap_test_items',
                'ordering': ['order_index'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentClapResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_clap_responses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAudioResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=50)),
                ('duration_seconds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('transcribed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='audio_responses', to='api.studentclapassignment')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='api.claptestitem')),
                ('response', models.OneToOneField(blank=True, db_column='response_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_file', to='api.studentclapresponse')),
            ],
            options={
                'db_table': 'student_audio_responses',
                'managed': True,
                'indexes': [models.Index(fields=['assignment', 'item'], name='student_aud_assignm_d0ecf4_idx'), models.Index(fields=['uploaded_at'], name='student_aud_uploade_a83f74_idx')],
                'unique_together': {('assignment', 'item')},
            },
        ),
    ]
