# Generated by Django 4.2.9 on 2026-02-22 04:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_admin_audio_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RULES_COMPLETE", "Rules Complete"),
                            ("LLM_PROCESSING", "LLM Processing"),
                            ("LLM_COMPLETE", "LLM Complete"),
                            ("REPORT_GENERATING", "Report Generating"),
                            ("REPORT_READY", "Report Ready"),
                            ("EMAIL_SENDING", "Email Sending"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("report_url", models.TextField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "assessment_submission",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=50)),
                ("old_status", models.CharField(blank=True, max_length=30, null=True)),
                ("new_status", models.CharField(blank=True, max_length=30, null=True)),
                ("worker_id", models.CharField(blank=True, max_length=100, null=True)),
                ("error_detail", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "audit_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DeadLetterQueue",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("error_message", models.TextField()),
                ("retry_count", models.IntegerField(default=0)),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "dead_letter_queue",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SubmissionScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("listening", "Listening"),
                            ("reading", "Reading"),
                            ("vocab", "Vocabulary & Grammar"),
                            ("writing", "Writing"),
                            ("speaking", "Speaking"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=4)),
                ("feedback_json", models.JSONField(blank=True, null=True)),
                (
                    "evaluated_by",
                    models.CharField(
                        choices=[("rule", "Rule Engine"), ("llm", "LLM")], max_length=10
                    ),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "llm_request_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
            options={
                "db_table": "submission_score",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="submissionscore",
            name="submission",
            field=models.ForeignKey(
                db_column="submission_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="api.assessmentsubmission",
            ),
        ),
        migrations.AddField(
            model_name="deadletterqueue",
            name="submission",
            field=models.ForeignKey(
                db_column="submission_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dlq_entries",
                to="api.assessmentsubmission",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="submission",
            field=models.ForeignKey(
                db_column="submission_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_events",
                to="api.assessmentsubmission",
            ),
        ),
        migrations.AddField(
            model_name="assessmentsubmission",
            name="assessment",
            field=models.ForeignKey(
                db_column="assessment_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="api.claptest",
            ),
        ),
        migrations.AddField(
            model_name="assessmentsubmission",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_submissions",
                to="api.user",
            ),
        ),
        migrations.AddIndex(
            model_name="submissionscore",
            index=models.Index(
                fields=["submission", "domain"], name="idx_score_submission"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submissionscore",
            unique_together={("submission", "domain")},
        ),
        migrations.AddIndex(
            model_name="deadletterqueue",
            index=models.Index(
                fields=["resolved", "created_at"], name="idx_dlq_unresolved"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["submission", "created_at"], name="idx_audit_submission"
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentsubmission",
            index=models.Index(
                fields=["status", "created_at"], name="idx_submission_status"
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentsubmission",
            index=models.Index(
                fields=["user", "assessment"], name="idx_submission_user"
            ),
        ),
    ]
