# Generated by Django 4.2.9 on 2026-03-06 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_assignment_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaudiofile',
            name='set_item',
            field=models.OneToOneField(blank=True, db_column='set_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_audio', to='api.clapsetitem'),
        ),
        migrations.AlterField(
            model_name='adminaudiofile',
            name='item',
            field=models.OneToOneField(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_audio', to='api.claptestitem'),
        ),
    ]
