# Generated by Django 4.2.9 on 2026-03-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_adminaudiofile_set_item_alter_adminaudiofile_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RULES_COMPLETE', 'Rules Complete'), ('LLM_PROCESSING', 'LLM Processing'), ('LLM_COMPLETE', 'LLM Complete'), ('LLM_FAILED', 'LLM Failed'), ('REPORT_GENERATING', 'Report Generating'), ('REPORT_READY', 'Report Ready'), ('EMAIL_SENDING', 'Email Sending'), ('COMPLETE', 'Complete')], default='PENDING', max_length=30),
        ),
    ]
