# Generated by Django 4.2.9 on 2026-03-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_component_attempt'),
        ('api', '0009_alter_assessmentsubmission_status'),
    ]

    operations = [
    ]
