# Generated by Django 4.2.9 on 2026-03-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_claptest_global_timer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='llm_failed_domains',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
